//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : Data
	/// Data Source    : Data
	/// Server Version : 3.24.0
	/// </summary>
	public partial class DataDB : LinqToDB.Data.DataConnection
	{
		public ITable<Emp> Emps { get { return this.GetTable<Emp>(); } }

		public DataDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DataDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DataDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DataDB(LinqToDbConnectionOptions<DataDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("Emp")]
	public partial class Emp
	{
		[Column("id"),        Nullable] public string Id        { get; set; } // varchar(32)
		[Column("name"),      Nullable] public string Name      { get; set; } // varchar(32)
		[Column("apartment"), Nullable] public string Apartment { get; set; } // varchar(32)
	}
}

#pragma warning restore 1591
